### ISSUE TITLE
Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory - ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/x86_64-linux/digest/md5.so

### ISSUE THREAD

**Issue by lpar** [Linuxbrew/linuxbrew#817]
I ran a `brew update` and suddenly nothing works:

```
% brew doctor
Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory - /home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/x86_64-linux/digest/md5.so
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.linuxbrew/Library/Homebrew/formulary.rb:1:in `<top (required)>'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.linuxbrew/Library/Homebrew/formula.rb:8:in `<top (required)>'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.linuxbrew/Library/Homebrew/diagnostic.rb:3:in `<top (required)>'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1:in `<top (required)>'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/meta/.linuxbrew/Library/brew.rb:21:in `require?'
/home/meta/.linuxbrew/Library/brew.rb:58:in `<main>'
% ls -la ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/x86_64-linux/digest/
total 684
drwxr-xr-x.  2 meta meta   4096 2016-01-04 12:51 .
drwxr-xr-x. 10 meta meta   4096 2016-01-04 12:51 ..
-rwxr-xr-x.  1 meta meta 139496 2016-01-04 12:51 bubblebabble.so
-rwxr-xr-x.  1 meta meta 133744 2016-01-04 12:50 md5.so
-rwxr-xr-x.  1 meta meta 134024 2016-01-04 12:50 rmd160.so
-rwxr-xr-x.  1 meta meta 134120 2016-01-04 12:50 sha1.so
-rwxr-xr-x.  1 meta meta 140608 2016-01-04 12:50 sha2.so
```

Same error for all commands. Tried with Ruby 2.2.3 as well, which I still have installed.

**Comment by lpar** [comment]
Seems to be something weird that has gone wrong with Ruby rather than linuxbrew per se, as loading `irb` and `require 'digest/md5'` gives the same error, but if anyone has any ideas...

**Comment by lpar** [comment]
I think the actual problem is that `md5.so` requires `libssl.so.1.0.0` according to `ldd`, but it's not finding that. It's at

    /home/meta/.linuxbrew/Cellar/openssl/1.0.2a-1/lib/libssl.so.1.0.0
    /home/meta/.linuxbrew/lib/libssl.so.1.0.0

**Comment by lpar** [comment]
If I symlink `.linuxbrew/Cellar/openssl/1.0.2a-1/lib/libssl.so.1.0.0` to `/home/meta/.linuxbrew/lib/` then `brew upgrade` gets a little further, it complains about `/home/meta/.linuxbrew/opt/curl/bin/curl: symbol lookup error: /home/meta/.linuxbrew/lib/libssl.so.1.0.0: undefined symbol: EVP_aes_128_cbc_hmac_sha256`

Which I think means the root problem is #737. `brew uninstall --force curl` worked around that. Let me know if there's anything I can do to help work out why the openssl upgrade broke everything.

**Comment by sjackman** [comment]
When upgrading `openssl` or `curl` a workaround a broken upgrade is to first `brew fetch openssl curl`. Linuxbrew needs to better handle this upgrade. It definitely should not leave your system in a broken state.
